CREATE TABLE USUARIO (
    ID BIGINT NOT NULL,
    NOME VARCHAR(100),
    EMAIL VARCHAR(200),
    PRIMARY KEY(ID)
);

INSERT INTO USUARIO (ID, NOME, EMAIL) VALUES (1, 'Jp Reis', 'jpreis@email.com');
INSERT INTO USUARIO (ID, NOME, EMAIL) VALUES (2, 'Lana KMF', 'lanakmf@email.com');