CREATE TABLE TOPICO (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(100) NOT NULL,
    MENSAGEM VARCHAR(500) NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    CURSO_ID BIGINT NOT NULL,
    USUARIO_ID BIGINT NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(CURSO_ID) REFERENCES CURSO(ID),
    FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID)
);
