CREATE TABLE USUARIO_ROLE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USUARIO_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

INSERT INTO USUARIO_ROLE VALUES (1,1,1)